[ -f "$HOME/.local/share/zap/zap.zsh" ] && source "$HOME/.local/share/zap/zap.zsh"

# history
HISTFILE=~/.zsh_history

# source files
plug "$HOME/.config/zsh/aliases.zsh"
plug "$HOME/.config/zsh/exports.zsh"

# plugins
# plug "marlonrichert/zsh-hist"
# bindkey '^[q' push-line-or-edit
# bindkey -r '^Q' '^[Q'

# plug "marlonrichert/zsh-autocomplete"

ZSH_AUTOSUGGEST_STRATEGY=( history )
plug "zsh-users/zsh-autosuggestions"
plug "zsh-users/zsh-syntax-highlighting"
plug "zap-zsh/vim"
plug "zap-zsh/zap-prompt"
plug "zap-zsh/fzf"
plug "zap-zsh/exa"

# plug "zsh-users/zsh-history-substring-search"
# bindkey "$terminfo[kcuu1]" history-substring-search-up
# bindkey "$terminfo[kcud1]" history-substring-search-down
# bindkey '^[[A' history-substring-search-up
# bindkey '^[[B' history-substring-search-down
# bindkey -M vicmd 'k' history-substring-search-up
# bindkey -M vicmd 'j' history-substring-search-down


eval "$(zoxide init zsh)"

# fnm
export PATH="/home/sabino/.local/share/fnm:$PATH"
eval "`fnm env`"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/sabino/mambaforge/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/sabino/mambaforge/etc/profile.d/conda.sh" ]; then
        . "/home/sabino/mambaforge/etc/profile.d/conda.sh"
    else
        export PATH="/home/sabino/mambaforge/bin:$PATH"
    fi
fi
unset __conda_setup

if [ -f "/home/sabino/mambaforge/etc/profile.d/mamba.sh" ]; then
    . "/home/sabino/mambaforge/etc/profile.d/mamba.sh"
fi
# <<< conda initialize <<<

