#!/bin/sh
# my aliases
alias t='tree -LC 1'
alias ta='tree -LCa 1'
alias tt='tree -LC 2'
alias ttt='tree -LC 3'
alias bat='batcat'

alias pshell='pipenv shell'

alias g='cd /home/sabino'
alias cl='clear'
alias r='rm -rfv'
alias nvim='/home/sabino/Downloads/nvim-linux64/bin/nvim'
alias v='/home/sabino/Downloads/nvim-linux64/bin/nvim'
alias v.='/home/sabino/Downloads/nvim-linux64/bin/nvim .'
alias ss='flameshot gui'
alias ide='/home/sabino/scripts/ide.sh'
alias ght='bat ~/.githubusertoken'
alias nvc='/home/sabino/Downloads/nvim-linux64/bin/nvim /home/sabino/.config//home/sabino/Downloads/nvim-linux64/bin/nvim/'

# go stuff
alias learngo='cd /home/sabino/learn/golang/'
alias ginit='go mod init'
alias gget='go get -u'
alias gtidy='go mod tidy'
alias gbuild='go build'

# conda
alias cact='conda activate'
alias cdeact='conda activate'

# alias clara='nvidia-docker run --shm-size=1G --ulimit memlock=-1 --ulimit stack=67108864 -it --rm -v /home/sabino/clara:/workspace -p 5001:6006 nvcr.io/nvidia/clara-train-sdk:v4.1 /bin/bash'
alias clara='nvidia-docker run --shm-size=1G --ulimit memlock=-1 --ulimit stack=67108864 -it --rm -v /home/sabino/ctrain:/workspace -p 5001:6006 nvcr.io/nvidia/clara-train-sdk:v4.1 /bin/bash'
alias ps='docker ps'
alias uptriton='docker-compose --env-file docker-compose.env -p aiaa_triton up --remove-orphans -d'
alias downtriton='docker-compose --env-file docker-compose.env -p aiaa_triton down --remove-orphans'
alias jupclara='cd /home/sabino/clara-train-examples/PyTorch/NoteBooks/AIAA/OHIF-Orthanc/'
# alias slicer='/home/sabino/Downloads/Slicer-5.1.0-2022-07-08-linux-amd64/Slicer'

# alias nvc='/home/sabino/Downloads/nvim-linux64/bin/nvim /home/sabino/.config//home/sabino/Downloads/nvim-linux64/bin/nvim/config.lua'
alias alac='/home/sabino/Downloads/nvim-linux64/bin/nvim /home/sabino/.config/alacritty/alacritty.yml'
alias kitconf='/home/sabino/Downloads/nvim-linux64/bin/nvim /home/sabino/.config/kitty/kitty.conf'
alias muxconf='/home/sabino/Downloads/nvim-linux64/bin/nvim /home/sabino/.config/tmux/'
alias zconf='/home/sabino/Downloads/nvim-linux64/bin/nvim /home/sabino/.config/zsh/'
alias powerlineconfig='/home/sabino/Downloads/nvim-linux64/bin/nvim /home/sabino/.config/powerline/'
alias oh='/home/sabino/Downloads/nvim-linux64/bin/nvim /home/sabino/.config/zsh/zsh-aliases'
alias ex='source /home/sabino/.config/zsh/.zshrc'

alias postman='./Downloads/Postman/Postman'

# git commands
alias gs='git status'
alias gadd='git add'
alias gcom='git commit'
alias gpush='git push -u origin master'
alias gpull='git pull'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# For when keys break
alias archlinx-fix-keys="sudo pacman-key --init && sudo pacman-key --populate archlinux && sudo pacman-key --refresh-keys"

# case "$(uname -s)" in

# Darwin)
# 	# echo 'Mac OS X'
# 	alias ls='ls -G'
# 	;;

# Linux)
# 	alias ls='ls --color=auto'
# 	;;

# CYGWIN* | MINGW32* | MSYS* | MINGW*)
# 	# echo 'MS Windows'
# 	;;
# *)
# 	# echo 'Other OS'
# 	;;
# esac
